/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * API version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bitbucket

import (
	"time"
)

type PipelineSchedule struct {
	Type_ string `json:"type"`
	// The UUID identifying the schedule.
	Uuid string `json:"uuid,omitempty"`
	// Whether the schedule is enabled.
	Enabled bool               `json:"enabled,omitempty"`
	Target  *PipelineRefTarget `json:"target,omitempty"`
	// The cron expression with second precision (7 fields) that the schedule applies. For example, for expression: 0 0 12 * * ? *, will execute at 12pm UTC every day.
	CronPattern string `json:"cron_pattern,omitempty"`
	// The timestamp when the schedule was created.
	CreatedOn time.Time `json:"created_on,omitempty"`
	// The timestamp when the schedule was updated.
	UpdatedOn time.Time `json:"updated_on,omitempty"`
}
