/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * API version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bitbucket

type PipelineSchedulePostRequestBody struct {
	Type_  string                                 `json:"type"`
	Target *PipelineSchedulePostRequestBodyTarget `json:"target"`
	// Whether the schedule is enabled.
	Enabled bool `json:"enabled,omitempty"`
	// The cron expression with second precision (7 fields) that the schedule applies. For example, for expression: 0 0 12 * * ? *, will execute at 12pm UTC every day.
	CronPattern string `json:"cron_pattern"`
}
