/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * API version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bitbucket

import (
	"time"
)

type APullRequestTask struct {
	Id        int32        `json:"id,omitempty"`
	CreatedOn time.Time    `json:"created_on"`
	UpdatedOn time.Time    `json:"updated_on"`
	State     string       `json:"state"`
	Content   *interface{} `json:"content"`
	Creator   *Account     `json:"creator"`
	Pending   bool         `json:"pending,omitempty"`
	// The ISO8601 timestamp for when the task was resolved.
	ResolvedOn time.Time    `json:"resolved_on,omitempty"`
	ResolvedBy *Account     `json:"resolved_by,omitempty"`
	Links      *interface{} `json:"links,omitempty"`
}
