/*
 * Bitbucket API
 *
 * Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, or even add custom UI add-ons into Bitbucket itself using the Connect framework.
 *
 * API version: 2.0
 * Contact: support@bitbucket.org
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package bitbucket

import (
	"time"
)

type WebhookSubscription struct {
	Type_ string `json:"type"`
	// The webhook's id
	Uuid string `json:"uuid,omitempty"`
	// The URL events get delivered to.
	Url string `json:"url,omitempty"`
	// A user-defined description of the webhook.
	Description string `json:"description,omitempty"`
	// The type of entity. Set to either `repository` or `workspace` based on where the subscription is defined.
	SubjectType string       `json:"subject_type,omitempty"`
	Subject     *interface{} `json:"subject,omitempty"`
	Active      bool         `json:"active,omitempty"`
	CreatedAt   time.Time    `json:"created_at,omitempty"`
	// The events this webhook is subscribed to.
	Events []string `json:"events,omitempty"`
	// Indicates whether or not the hook has an associated secret. It is not possible to see the hook's secret. This field is ignored during updates.
	SecretSet bool `json:"secret_set,omitempty"`
	// The secret to associate with the hook. The secret is never returned via the API. As such, this field is only used during updates. The secret can be set to `null` or \"\" to remove the secret (or create a hook with no secret). Leaving out the secret field during updates will leave the secret unchanged. Leaving out the secret during creation will create a hook with no secret.
	Secret string `json:"secret,omitempty"`
}
